development:
  adapter: postgresql
  encoding: unicode
  database: papp_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: papp_test
  pool: 5
  username: postgres
  password: password
